[package]
name = "process_video"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
ndarray = "0.15.6"
opencv = "0.92.1"
ort = { version = "2.0.0-rc.4", features = ["cuda"] }
tracing-subscriber = "0.3.18"
